spring:
  cache:
    caffeine:
      spec: expireAfterAccess=600s
    cache-names: breeds,subBreeds,breedsWithoutSubBreeds,breedSubBreeds,breedImages
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  r2dbc:
    url: r2dbc:h2:mem:///dogdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:

logging:
  level:
    com.epam.mentoring.kotlin: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.web: DEBUG

management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

